### PR TITLE
PostgreSQL support added

### PR DESCRIPTION
**Pull request by ColonelMoutarde**
## PR Checklist

- [x] The commit message follows our guidelines: https://github.com/Smile-SA/gdpr-dump/blob/main/CONTRIBUTING.md.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type

What kind of change does this PR introduce?

PostgreSQL support added
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```
## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information
Drop support of php8.1

### CODE REVIEW

**Comment by ColonelMoutarde** [comment]
I need help for end this feature

**Comment by guvra** [comment]
Hi,

The PR contains a lot of changes that don't have anything to do with adding postgresql (dropping php 8.1, adding readonly classes, changing indentation of a lot of constructors...). It makes the PR nearly impossible to properly review.

Also, after a quick glance, it looks like you're using a php dumper (spatie/db-dumber) that doesn't provide any way to transform values before they are dumped. It's just a wrapper on top of mysqldump/pg_dump, so it's useless in the context of GdprDump. The converters/filters features rely on the hooks provided by mysqldump-php.

IIRC we already discussed about this a few years ago, but adding proper postgresql support is extremely complex, you'd need to reimplement pgdump in a custom php library.

**Comment by ColonelMoutarde** [comment]
> Hi,
> 
> The PR contains a lot of changes that don't have anything to do with adding postgresql (dropping php 8.1, adding readonly classes, changing indentation of a lot of constructors...). It makes the PR nearly impossible to properly review.
> 
> Also, after a quick glance, it looks like you're using a php dumper (spatie/db-dumber) that doesn't provide any way to transform values before they are dumped. It's just a wrapper on top of mysqldump/pg_dump, so it's useless in the context of GdprDump. The converters/filters features rely on the hooks provided by mysqldump-php.
> 
> IIRC we already discussed about this a few years ago, but adding proper postgresql support is extremely complex, you'd need to reimplement pgdump in a custom php library.

Hello,
I switched some classes to readonly because it seemed appropriate and as I needed a feature that was only available in php8.2 (`DriversEnum::DRIVER_MYSQL->value`) I took the opportunity to modernize the code a bit. 
Granted, it makes the PR very big)
Concerning pgdump, it's actually the hook that's giving me trouble. I thought that by initiating development we could work together to finish it.

Some of the code you've developed shows that your original intention is to manage several DBMSs. Let's go ahead and implement at least the two main ones together. I know you might have this need internally at Smile...

**Comment by guvra** [comment]
> I thought that by initiating development we could work together to finish it.

I just explained in my previous reply why we don't plan to do this.

Before adding pgsql support, you'd need to reimplement pg_dump into a php library.
So basically, reimplement [this](https://github.com/postgres/postgres/tree/master/src/bin/pg_dump) (dozens of thousands of lines of codes) in php. This is absolutely not worth it. Use tools dedicated to postgresql instead. After a quick search, it seems like there are already a few anonymization tools that exist for postgresql.

**Comment by guvra** [comment]
To add to my previous reply, if such a lib existed, we would definitely add support for postgresql.
Until then, it's not a planned feature.

**Pull request closed without merging**
