### PR TITLE
remove double quotes in getTableNames() query

### LINKED ISSUE #38: Exception occured in \Smile\GdprDump\Database\Metadata\MysqlMetadata::getTableNames
### Preconditions
GdprDump Version: 2.0.3
PHP Version: 7.4.7
Mysql Version: 8.0.19

### Steps to reproduce

1. Run `php gdpr-dump.phar rgpd_dump_config.yaml -vv`

### Expected result

1. Expects sql dump file generation

### Actual result

1. [logs]
```log
developer@srv:~$ php gdpr-dump.phar rgpd_dump_config.yaml -vv
In AbstractMySQLDriver.php line 2:

  [Doctrine\DBAL\Exception\InvalidFieldNameException]
  An exception occurred while executing 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE="BASE TABLE" AND TABLE_SCHEMA=? ORDER BY TABLE_NAME ASC' with params ["dbname"]:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause'

Exception trace:
  at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:2
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:2
 Doctrine\DBAL\DBALException::wrapException() at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:2
 Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:2
 Doctrine\DBAL\Connection->handleExceptionDuringQuery() at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:2
 Doctrine\DBAL\Statement->execute() at phar:///home/developer/gdpr-dump.phar/src/Database/Metadata/MysqlMetadata.php:2
 Smile\GdprDump\Database\Metadata\MysqlMetadata->getTableNames() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->findTablesByName() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->resolveTablesData() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->processTablesData() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->process() at phar:///home/developer/gdpr-dump.phar/src/Dumper/SqlDumper.php:2
 Smile\GdprDump\Dumper\SqlDumper->dump() at phar:///home/developer/gdpr-dump.phar/src/Console/Command/DumpCommand.php:2
 Smile\GdprDump\Console\Command\DumpCommand->execute() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Command/Command.php:2
 Symfony\Component\Console\Command\Command->run() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->doRun() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->run() at phar:///home/developer/gdpr-dump.phar/src/AppKernel.php:2
 Smile\GdprDump\AppKernel->run() at phar:///home/developer/gdpr-dump.phar/bin/gdpr-dump:2
 require() at /home/developer/gdpr-dump.phar:6
In Exception.php line 2:

  [Doctrine\DBAL\Driver\PDO\Exception (42S22)]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause'

Exception trace:
  at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:2
 Doctrine\DBAL\Driver\PDO\Exception::new() at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:2
 Doctrine\DBAL\Driver\PDOStatement->execute() at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:2
 Doctrine\DBAL\Statement->execute() at phar:///home/developer/gdpr-dump.phar/src/Database/Metadata/MysqlMetadata.php:2
 Smile\GdprDump\Database\Metadata\MysqlMetadata->getTableNames() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->findTablesByName() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->resolveTablesData() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->processTablesData() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->process() at phar:///home/developer/gdpr-dump.phar/src/Dumper/SqlDumper.php:2
 Smile\GdprDump\Dumper\SqlDumper->dump() at phar:///home/developer/gdpr-dump.phar/src/Console/Command/DumpCommand.php:2
 Smile\GdprDump\Console\Command\DumpCommand->execute() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Command/Command.php:2
 Symfony\Component\Console\Command\Command->run() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->doRun() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->run() at phar:///home/developer/gdpr-dump.phar/src/AppKernel.php:2
 Smile\GdprDump\AppKernel->run() at phar:///home/developer/gdpr-dump.phar/bin/gdpr-dump:2
 require() at /home/developer/gdpr-dump.phar:6
In PDOStatement.php line 2:

  [PDOException (42S22)]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause'

Exception trace:
  at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:2
 PDOStatement->execute() at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:2
 Doctrine\DBAL\Driver\PDOStatement->execute() at phar:///home/developer/gdpr-dump.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:2
 Doctrine\DBAL\Statement->execute() at phar:///home/developer/gdpr-dump.phar/src/Database/Metadata/MysqlMetadata.php:2
 Smile\GdprDump\Database\Metadata\MysqlMetadata->getTableNames() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->findTablesByName() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->resolveTablesData() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->processTablesData() at phar:///home/developer/gdpr-dump.phar/src/Dumper/Config/ConfigProcessor.php:2
 Smile\GdprDump\Dumper\Config\ConfigProcessor->process() at phar:///home/developer/gdpr-dump.phar/src/Dumper/SqlDumper.php:2
 Smile\GdprDump\Dumper\SqlDumper->dump() at phar:///home/developer/gdpr-dump.phar/src/Console/Command/DumpCommand.php:2
 Smile\GdprDump\Console\Command\DumpCommand->execute() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Command/Command.php:2
 Symfony\Component\Console\Command\Command->run() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->doRun() at phar:///home/developer/gdpr-dump.phar/vendor/symfony/console/Application.php:2
 Symfony\Component\Console\Application->run() at phar:///home/developer/gdpr-dump.phar/src/AppKernel.php:2
 Smile\GdprDump\AppKernel->run() at phar:///home/developer/gdpr-dump.phar/bin/gdpr-dump:2
 require() at /home/developer/gdpr-dump.phar:6
gdpr-dump <config_file>...
```

### PR DESCRIPTION
**Pull request by bertrand-leroux**
## PR Checklist

- [x] The commit message follows our guidelines: https://github.com/Smile-SA/gdpr-dump/blob/master/CONTRIBUTING.md.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added / updated (for bug fixes / features).

## PR Type
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by guvra** [comment]
@bertrand-leroux Thanks for the PR, I've amended your commit, could you check it's still working on the server that is affected by the bug?

**Comment by guvra** [comment]
@bertrand-leroux reping in case you missed the notifciation :smiley:

**Comment by bertrand-leroux** [comment]
You're welcome GuVra, and yes : it's still working !
I might be opening another issue concerning again double quotes in dump generated file, but it may come from ifsnop/mysqldump-php

**Comment by guvra** [comment]
@bertrand-leroux Did you try the following fix? https://www.digitalocean.com/community/questions/sql-requests-with-double-quotes-not-working-with-managed-database

**Comment by bertrand-leroux** [comment]
I guess that's indeed what I need : Thx a lot !

**Pull request merged**
