### PR TITLE
Add link to github template listing

### PR DESCRIPTION
**Pull request by amenk**
Doc Update: Introduce community templates

(Follow up #46)

### CODE REVIEW

**Comment by amenk** [comment]
What do you think? Can we define that as a standard to discover templates?

**Comment by guvra** [comment]
@amenk Yes it seems all good, I just didn't have time to work on this recently.
I'll review it tomorrow.

**Comment by amenk** [comment]
@guvra sure thanks, will try to make more templates then :D

**Comment by guvra** [comment]
@amenk It's merged, and I moved it to the README, it will be more visible :)

FYI i've also added a documentation on how to compile the phar:
https://github.com/Smile-SA/gdpr-dump/blob/master/docs/04-phar.md

**Pull request merged**
