### PR TITLE
Adds configurability of faker locale

### PR DESCRIPTION
**Pull request by moay**
## PR Checklist

Please check if your pull request fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/Smile-SA/gdpr-dump/blob/master/CONTRIBUTING.md.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
The faker converters always use `en_US` as default locale.

Issue Number: N/A

## What is the new behavior?
The faker locale can be configured in the dump configuration. It still defaults to `en_US`, but the locale *can* be configured.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by guvra** [comment]
Hi,

Thanks for the contribution.
However, there is a design issue here.

The recommended way to install this tool is to use the compiled phar.
Since v2.1.0, only one Faker locale is included in the phar file (en_US by default).
See here: https://github.com/Smile-SA/gdpr-dump/blob/2.1.0/src/Phar/Compiler.php#L111
This helped reducing the total size of the phar (~70% reduction).

Because of this, it is impossible to change the faker locale dynamically.
To change the locale, you need to do the following steps:

1. Edit the value in [app/config/services.yaml](https://github.com/Smile-SA/gdpr-dump/blob/2.1.0/app/config/services.yaml#L5)
2. Compile the phar, with the following script:
    ```
    php -d phar.readonly=off bin/compile
    ```

This will generate a phar file that includes (and uses) the faker locale you need.

This is currently not documented though.
We could add this process to the documentation.

**Comment by moay** [comment]
Hi @guvra,

thanks for your review. From a developer perspective, I (by far) prefer using composer and calling the tool using `vendor/bin/gdpr-dump`. Also, I don't care about the package size like at all. ;-)

Using composer makes my life a lot easier. Also I don't have to keep .phar files in my repos (which unnecessarily blows them up for a dependency I don't need).

In addition to that, we actually have use cases where we want to have different localizations per dump. Having to use different phars for that seems a bit awkward.

I do understand that this is a design issue, though. Maybe, one could think about allowing the use of the faker locale only when using the composer package? If you do not want to split things up here and definitely want to keep using the .phar installation as primary way, I'd at least document the localization feature. :-)

**Comment by moay** [comment]
Another thought: One could add a check for the available locales that are loaded and output a proper error message if the given locale is not available. This would allow to use the feature both when using the composer library and with a .phar build where only `en_US` is available by default.

I could prepare the check and add it to the PR? Setting the locale in the services.yaml would need to be reenabled of course, I'd take care of that.

**Comment by guvra** [comment]
> If you do not want to split things up here and definitely want to keep using the .phar installation as primary way, I'd at least document the localization feature. :-)

I agree that this should be documented, regardless of the implementation.

> Using composer makes my life a lot easier. Also I don't have to keep .phar files in my repos (which unnecessarily blows them up for a dependency which I could use via composer).

There are two reasons why I recommend using the phar file:

- It allows to remain "bleeding edge" regarding to package dependencies.
- In my opinion, this tool should not be installed within the project files on a production environment. It should be installed and maintained separately. The web user should definitely not have the option to run the gdpr-dump command.

> I (by far) prefer using composer and calling the tool using vendor/bin/gdpr-dump

It's actually technically possible to use the phar file with composer, but that would require a bit of extra work.
We would need to create a 2nd repository that includes only the phar file (e.g. smile/gdpr-dump-dist).

Then, to install it in a project:

```
composer require smile/gdpr-dump-dist
```

And you would run it as usual:

```
vendor/bin/gdpr-dump
```

The only difference is that the binary would be the phar file itself.

There are already a few dev tools that work like this (e.g. phpstan).
IMO it's the best of both worlds.

But I'm still hesitant to implement this, precisely because I think it's "dangerous" to have the gdpr-dump command reside in the vendor directory and be executable by the web user.

> One could add a check for the available locales that are loaded and output a proper error message if the given locale is not available. This would allow to use the feature both when using the composer library and with a .phar build where only en_US is available by default.

That is indeed a possibility.
The locale in services.yaml would then be the default locale.

Problem is : most ppl would install the tool using the recommended way and have trouble understanding why changing the locale doesn't work, and how to solve this issue (people are not good at RTFM).

One last thing: i don't remember if this is documented somewhere, but you should only use Faker if your database is very small (or at least the tables you anonymize). Faker is **extremely** slow (and I don't exagerate when I say "extremely"). I did some benchmark at the start of the project, it is so slow that dumping a very big database is next to impossible.

This is why the default template use it very scarcely.

**Comment by moay** [comment]
I see your concerns and understand why you have been going this way. I have some different feelings, which you of course don't have to share, but I'd like to try to explain them in case you are open for an outside perspective. 

> It allows to remain "bleeding edge" regarding to package dependencies.

This is a valid point.

>In my opinion, this tool should not be installed within the project files on a production environment. It should be installed and maintained separately. The web user should definitely not have the option to run the gdpr-dump command.

I think that there are two different situations here. Running the tool as is is of course a valid use case and in this case I strongly get the need to have the .phar-file as an executable binary. Our use case is different than that, we are using the library within a PHP cli tool. Currently, we are still using it via the binary, but we can include the package via composer, which seemed quicker and easier (and is versioned and automatically updated).

Not having the tool on a production environment seems like a good idea, but this is a general point which will not be prevented by going the .phar way. I agree with you that the tool shouln't be held within a webservice and that backing up your stuff should be executed somewhere else (we currently create our own cli tool for this which will then be executed remotely), but there (for me) seems not to be a big difference in using the phar vs composer in this case.


If by the "web user" you mean the final user of a web service - I agree. But they should never be able to use anything from the vendor folder. If you mean the hosting os web user, I don't see any points where this would be discouraged. Seems like a valid use case to be, to f.i. have a cronjob on the web user that triggers the dump. 🤔 

> But I'm still hesitant to implement this, precisely because I think it's "dangerous" to have the gdpr-dump command reside in the vendor directory and be executable by the web user.

Again, if I get you right, you are having concerns about the vendor folder being available via some url. So that I could call `https://example.com/vendor/bin/gdpr-dump`, right? If so, I'd strongly opt for the composer way. In all modern frameworks I know, the vendor folder is outside the public folder as it should be. Having stuff accessible that should not be accessible is an error that beginners are more prone to than experienced developers. When placing the .phar, beginners are forced to select a location and will way more often end up placing it in a bad location than using composer, where standards and conventions tend to prevent this kind of error.

> Problem is : most ppl would install the tool using the recommended way and have trouble understanding why changing the locale doesn't work, and how to solve this issue (people are not good at RTFM).

I think that people who are not able to RTFM will never get to the point where they might use the faker converters nor get the idea that setting the faker locale might be a thing. Also the error message that will be thrown when using a non existing locale could be clear and informative, for example: `The locale ru_RU is not bundled with this version of faker and gdpr-dump. It might not exist (see the available locales here) or you might need to build gdpr-dump with support for that locale. You'll find more information on that topic here: [Deeplink]`.

What do you think?

**Comment by moay** [comment]
One addition: I'm not having any performance issues with faker so far. Just executed a complete anonymization of a db with ~150 MB of size (yes, there are bigger ones) which ran in just some seconds without any problems.

**Comment by guvra** [comment]
> If by the "web user" you mean the final user of a web service - I agree

No, I was refering to the Apache/nginx user, which runs the web application.
And refering to projects where gdpr-dump is installed within the application. e.g. adding smile/gdpr-dump to a Laravel application.

I don't recommend doing this, it's terrible security-wise.
This app must be used as a standalone application.

But your use case is different. If I understood correctly, you do use the application as a standalone, but you'd prefer to install it with composer instead of using a phar file.

> Also the error message that will be thrown when using a non existing locale could be clear and informative, for example: The locale ru_RU is not bundled with this version of faker and gdpr-dump. It might not exist (see the available locales here) or you might need to build gdpr-dump with support for that locale. You'll find more information on that topic here: [Deeplink].

Yes, it could be useful, I added the review of this PR in my todo list, I can't work on this at this moment unfortunately.

> One addition: I'm not having any performance issues with faker so far. Just executed a complete anonymization of a db with ~150 MB of size (yes, there are bigger ones) which ran in just some seconds without any problems.

It's a quite a small database.

For example, if a faker formatter is 10x slower than an optimized converter, you won't notice the difference unless there are a lot of values to process (e.g. millions of values). The more values you process, the more you notice the difference (e.g. 3 minute vs 30 minutes).

**Comment by moay** [comment]
Yes, you got the use case correct. In this scenario we actually really don't mind the additional MB when not using the phar.

I'll add a proposition for the exception with unknown locales tomorrow.

**Comment by guvra** [comment]
I've added a commit that adds the option to compile phar with multiples locales.

services.yaml:

```yaml
    faker.locale: 'en_US'
    faker.installed_locales:
        - 'en_US'
```

faker.locale is the default Faker locale.
faker.installed_locales is the list of Faker locales added to the phar file.
If the value of `faker.locale` is not present in `faker.installed_locales`, an error message is displayed.

For example, to use en_US, de_DE, it_IT, es_ES and fr_FR: 

1. Add the locale in services.yaml:
    ```yaml
    faker.locale: 'en_US'
    faker.installed_locales:
        - 'en_US'
        - 'de_DE'
        - 'it_IT'
        - 'es_ES'
        - 'fr_FR'
    ```
2. Run the compiler: `php -d phar.readonly=off bin/compile`

The file phar is generated at the following location: build/dist/gdpr-dump.phar.

**Pull request merged**
