### PR TITLE
Allow referencing environment variables in the configuration

### PR DESCRIPTION
**Pull request by guvra**
Add support for setting an environment variable named `GDPR_DUMP_DATABASE_PASSWORD`.

It takes the precedence over the value from the configuration file (if any).
This allows to set the database password from shell scripts.

### CODE REVIEW

**Comment by guvra** [comment]
@floretan would this PR solve your issue the database password?

**Comment by floretan** [comment]
Thank you @guvra! Yes, I believe this would work. 

However, having the password in an environment variable and the rest of the database credentials in the configuration file would be a bit confusing. 

A more generic approach with support for environment variables in the configuration file could allow for a cleaner integration in a variety of contexts. I could imagine the configuration file looking like this:
```
database:
    host: '%env(DB_HOST)%'
    user: '%env(DB_USER)%'
    password: '%env(DB_PASS)%'
    name: '%env(DB_NAME)%'
```
This would also allow to use existing environment variables, rather than having to duplicate them into a new one just for gdpr-dump.

**Comment by guvra** [comment]
@floretan I will check if it is possible to add an env var processor.

I won't replace the whole config namespace with symfony components, there are too much dependencies (config, dependency-injection, dotenv...) for such a small feature. Also, it does not seem to be easy to implement outside of a symfony bundle.

**Comment by guvra** [comment]
@floretan Done :)

You can use environment variables with the following syntax:

```yaml
database:
    host: '%env(DATABASE_HOST)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
    name: '%env(DATABASE_NAME)%'
```

You can also set the variable type with the following syntax:

```yaml
tables:
    cache:
        truncate: '%env(bool:TRUNCATE_CACHE_TABLE)%'
```

Available types: string (default), bool, int, float, json.

The JSON type allows using array values. For example:

```yaml
tables_blacklist: '%env(json:TABLES_BLACKLIST)%'
```

Example value of the environment variable: `["table1", "table2", "table3"]`.

**Comment by floretan** [comment]
Nice, I tried it out and it works great!

**Pull request merged**
